In [1]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [2]:
my_arr = np.arange(1_000_000)

In [3]:
my_list = list(range(1_000_000))

In [4]:
%timeit my_arr2 = my_arr * 2

652 µs ± 6.08 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
%timeit my_list2 = [x * 2 for x in my_list]

23.5 ms ± 260 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [7]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [8]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [9]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [10]:
data.shape

(2, 3)

In [11]:
data.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [12]:
data.dtype

dtype('float64')

In [ ]:
Remember to use dtype to see type for numpy objects