In [3]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [2]:
my_arr = np.arange(1_000_000)

In [3]:
my_list = list(range(1_000_000))

numpy algos are faster and use less memory than regular python

In [4]:
%timeit my_arr2 = my_arr * 2

652 µs ± 6.08 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
%timeit my_list2 = [x * 2 for x in my_list]

23.5 ms ± 260 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [7]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [8]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [9]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [10]:
data.shape

(2, 3)

In [11]:
data.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [12]:
data.dtype

dtype('float64')

Remember to use dtype to see type for numpy objects

### Creating ndarrays

In [1]:
data1= [6, 7.5, 8, 0,1]

In [4]:
arr1 = np.array(data1)

In [5]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

#### multi-dimensional array from equal length lists

In [7]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [9]:
arr2 = np.array(data2)

In [10]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr2.ndim

2

In [12]:
arr2.shape

(2, 4)

In [13]:
arr1.dtype

dtype('float64')

In [14]:
arr2.dtype

dtype('int64')

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create array with a given size

In [18]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [19]:
np.empty((2, 3, 2))

array([[[0.00000000e+000, 1.00937611e-320],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.61590357e+184]],

       [[5.58670628e-091, 1.52045380e-051],
        [6.54775654e-043, 1.45071711e+165],
        [3.99910963e+252, 1.46030983e-319]]])

### Important Array Functions

* array:	Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a data type or explicitly 
            specifying a data type; copies the input data by default
* asarray:	Convert input to ndarray, but do not copy if the input is already an ndarray
* arange:	Like the built-in range but returns an ndarray instead of a list
* ones, ones_like:	Produce an array of all 1s with the given shape and data type; ones_like takes another array and produces a ones array 
            of the same shape and data type
* zeros, zeros_like:	Like ones and ones_like but producing arrays of 0s instead
* empty, empty_like:	Create new arrays by allocating new memory, but do not populate with any values like ones and zeros
* full, full_like:  Produce an array of the given shape and data type with all values set to the indicated "fill value"; full_like takes 
                    another array and produces a filled array of the same shape and data type
* eye, identity:	Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)

### Data Types for ndarrays

In [25]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [26]:
arr1.dtype

dtype('float64')

In [27]:
arr2.dtype

dtype('int32')

In [29]:
arr = np.array([1, 2, 3, 4, 5])

In [30]:
arr.dtype

dtype('int64')

In [31]:
float_arr = arr.astype(np.float64)

In [32]:
float_arr

array([1., 2., 3., 4., 5.])

In [33]:
float_arr.dtype

dtype('float64')

In [34]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [35]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [37]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

Cast Strings that are numbers to appopriate type

In [38]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)

In [39]:
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [40]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

### Arithmetic with Arrays

In [4]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [5]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [6]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [7]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr = np.arange(10)

In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr[5:8]

array([5, 6, 7])

In [14]:
arr[5:8] = 12

In [15]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

### Slices are view inside original array, change to slice changes original array

In [16]:
arr_slice = arr[5:8]

In [17]:
arr_slice[1] = 12345

In [18]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])